// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6ht9QMgO5jJr_jsLQeIrPq91xhaQzXoA',
    appId: '1:621537680556:web:3afffdec7d471304c95309',
    messagingSenderId: '621537680556',
    projectId: 'appsciencelifter',
    authDomain: 'appsciencelifter.firebaseapp.com',
    storageBucket: 'appsciencelifter.firebasestorage.app',
    measurementId: 'G-CH2LQP4S6C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvrRipVSQev4KylLWnzubJcLsaWqIi3NE',
    appId: '1:621537680556:android:7d513ec38715c8ecc95309',
    messagingSenderId: '621537680556',
    projectId: 'appsciencelifter',
    storageBucket: 'appsciencelifter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFxCTX-_JQ2Laun7oKevXSiol2JQDEeZ4',
    appId: '1:621537680556:ios:4f289bd1933bb421c95309',
    messagingSenderId: '621537680556',
    projectId: 'appsciencelifter',
    storageBucket: 'appsciencelifter.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFxCTX-_JQ2Laun7oKevXSiol2JQDEeZ4',
    appId: '1:621537680556:ios:4f289bd1933bb421c95309',
    messagingSenderId: '621537680556',
    projectId: 'appsciencelifter',
    storageBucket: 'appsciencelifter.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

}